article/config/routes.rb
Article::Engine.routes.draw do
  
  resources :categories


  resources :articles


end

article/app/models/article/article.rb
module Article
  class Article < ActiveRecord::Base
    has_many :relations_categories, dependent: :destroy
    has_many :categories, :through => :relations_categories
    attr_accessible :attached, :content, :is_active, :picture, :picture_slider, :preambula, :short_content, :title  
    validates :content,:title,:short_content,:preambula, presence:true
    validates :picture,:picture_slider, allow_blank: true, format:{
    with: %r{\.(gif|jpg|png|jpeg)$}i
  }
  end
end

article/app/models/article/category.rb
module Article
  class Category < ActiveRecord::Base
    has_many :relations_categories
    has_many :articles, :through => :relations_categories
    validates :name, presence:true
    attr_accessible :name
  end
end

article/app/models/article/relations_category.rb
module Article
  class RelationsCategory < ActiveRecord::Base
    belongs_to :articles       
    belongs_to :categories 
    validates :article_id, :category_id, presence:true
    attr_accessible :article_id, :category_id
  end
end

article/app/models/article/relations_category_news.rb
module Article
  class RelationsCategoryNews < ActiveRecord::Base
    attr_accessible :article_id, :category_id
  end
end

article/app/controllers/article/application_controller.rb
module Article
  class ApplicationController < ActionController::Base
  end
end

article/app/controllers/article/articles_controller.rb
require_dependency "article/application_controller"

module Article
  class ArticlesController < ApplicationController
    # GET /articles
    # GET /articles.json
    def index
      @articles = Article.all 
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @articles }
      end
    end
  
    # GET /articles/1
    # GET /articles/1.json
    def show
      @article = Article.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @article }
      end
    end
  
    # GET /articles/new
    # GET /articles/new.json
    def new
      @article = Article.new  
      @categories = Category.all
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @article }
      end
    end
  
    # GET /articles/1/edit
    def edit
      @article = Article.find(params[:id])
      @categories = Category.all
      @selected_categories = RelationsCategory.where(:article_id => params[:id]).select("category_id").collect{|x| x.category_id}
    end
  
    # POST /articles
    # POST /articles.json
    def add_rels (article_id, categories)
      if categories
        categories.each do |cat|
          cs = RelationsCategory.new(:category_id=>cat,:article_id=>article_id)
          if cs.valid?
            cs.save
          else
            @errors += cs.errors
          end
        end
      end
    end

    def create
      @article = Article.new(params[:article])
      respond_to do |format|
        if @article.save
          add_rels @article.id, params[:categories]
          format.html { redirect_to @article, notice: 'Article was successfully created.' }
          format.json { render json: @article, status: :created, location: @article }  
        else
          @categories = Category.all
          format.html { render action: "new" }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /articles/1
    # PUT /articles/1.json
    def update
      @article = Article.find(params[:id])
  
      respond_to do |format|
        if @article.update_attributes(params[:article])
          rels = RelationsCategory.where(:article_id => params[:id]) 
          if rels
            rels.each{|t| t.destroy}
          end
          add_rels params[:id],params[:categories]
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { head :no_content }
        else
          @categories = Category.all
          format.html { render action: "edit" }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /articles/1
    # DELETE /articles/1.json
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
  
      respond_to do |format|
        format.html { redirect_to articles_url }
        format.json { head :no_content }
      end
    end
  end
end

article/app/controllers/article/categories_controller.rb
require_dependency "article/application_controller"

module Article
  class CategoriesController < ApplicationController
    # GET /categories
    # GET /categories.json
    def index
      @categories = Category.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @categories }
      end
    end
  
    # GET /categories/1
    # GET /categories/1.json
    def show
      @category = Category.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @category }
      end
    end
  
    # GET /categories/new
    # GET /categories/new.json
    def new
      @category = Category.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @category }
      end
    end
  
    # GET /categories/1/edit
    def edit
      @category = Category.find(params[:id])
    end
  
    # POST /categories
    # POST /categories.json
    def create
      @category = Category.new(params[:category])
  
      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render json: @category, status: :created, location: @category }
        else
          format.html { render action: "new" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /categories/1
    # PUT /categories/1.json
    def update
      @category = Category.find(params[:id])
  
      respond_to do |format|
        if @category.update_attributes(params[:category])
          format.html { redirect_to @category, notice: 'Category was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /categories/1
    # DELETE /categories/1.json
    def destroy
      @category = Category.find(params[:id])
      @category.destroy
  
      respond_to do |format|
        format.html { redirect_to categories_url }
        format.json { head :no_content }
      end
    end
  end
end

article/app/helpers/article/application_helper.rb
module Article
  module ApplicationHelper
  end
end

article/app/helpers/article/articles_helper.rb
module Article
  module ArticlesHelper
  end
end

article/app/helpers/article/categories_helper.rb
module Article
  module CategoriesHelper
  end
end

article/app/views/article/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li style="color:red;"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <% if @selected_categories %>
      <% options = @categories.map do |opt| %>
        <% if @selected_categories.include?(opt[:id]) %>
          <%  "<option value=\"#{opt[:id]}\" selected=\"selected\">#{opt[:name]}</option>" %>
        <% else %>
          <%  "<option value=\"#{opt[:id]}\">#{opt[:name]}</option>"%>
        <% end %>
      <% end %>
      <%= select_tag "categories", options.join(" ").html_safe,:multiple => true %>
    <% else %>
      <%=select_tag "categories", options_from_collection_for_select(@categories, 'id', 'name'), :multiple => true %>
    <% end %>
  </div>
   
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :picture_slider %><br />
    <%= f.text_field :picture_slider %>
  </div>
  <div class="field">
    <%= f.label :preambula %><br />
    <%= f.text_area :preambula,  :rows => "10",:cols=>"45" %>
  </div>
  <div class="field">
    <%= f.label :short_content %><br />
    <%= f.text_area :short_content,  :rows => "10",:cols=>"45" %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content,:cols=>"100" %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :attached %><br />
    <%= f.check_box :attached %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

article/app/views/article/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

article/app/views/article/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Picture</th>
    <th>Picture slider</th>
    <th>Preambula</th>
    <th>Short content</th>
    <th>Content</th>
    <th>Is active</th>
    <th>Attached</th>
    <th>Is active</th>
    <th>Category</th>
    <th>Actions</th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.picture %></td>
    <td><%= article.picture_slider %></td>
    <td><%= article.preambula %></td>
    <td><%= article.short_content %></td>
    <td><%= article.content %></td>
    <td><%= article.is_active %></td>
    <td><%= article.attached %></td>
    <td><%= article.is_active %></td>
    <td><% article.relations_categories.each do |t|%>
            <%=t.category_id %>,
        <% end %>
    </td>
    <td><%= link_to 'Show', article %>&nbsp;<%= link_to 'Edit', edit_article_path(article) %>&nbsp;<%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

article/app/views/article/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

article/app/views/article/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Picture:</b>
  <%= @article.picture %>
</p>

<p>
  <b>Picture slider:</b>
  <%= @article.picture_slider %>
</p>

<p>
  <b>Preambula:</b>
  <%= @article.preambula %>
</p>

<p>
  <b>Short content:</b>
  <%= @article.short_content %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>

<p>
  <b>Is active:</b>
  <%= @article.is_active %>
</p>

<p>
  <b>Attached:</b>
  <%= @article.attached %>
</p>

<p>
  <b>Is active:</b>
  <%= @article.is_active %>
</p>

 


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

article/app/views/article/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

article/app/views/article/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

article/app/views/article/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

article/app/views/article/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

article/app/views/article/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

article/app/views/layouts/article/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Article</title>
  <%= stylesheet_link_tag    "article/application", :media => "all" %>
  <%= javascript_include_tag "article/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>